### ISSUE TITLE
Referenced schema with reference

### ISSUE THREAD

**Issue by darichey** [leadpony/justify#20]
I am having difficulties resolving references. Specifically, I have a schema `foo` which references schema `bar` which references schema `baz`. The reference is resolved fine when reading `bar`, but not when reading `foo`.

[Here ](https://gist.github.com/darichey/90baa0c9c8430063373967c4f0ae34da)is an example, also with the code I am using (mostly copied from [the example](https://github.com/leadpony/justify-examples/blob/master/justify-examples-schemaresolver/src/main/java/org/leadpony/justify/examples/schemaresolver/Example.java)).
The schemas are in a directory `./schema` and the instances are in a directory `./sample`.

Here is the output of the included program:
```
{"qux":3}
{"baz":{"qux":3}}
Exception in thread "main" org.leadpony.justify.api.JsonValidatingException: [7,31] The schema reference "baz.schema.json"(baz.schema.json) cannot be resolved.
	at org.leadpony.justify.internal.schema.io.AbstractSchemaReader.dispatchProblems(AbstractSchemaReader.java:80)
	at org.leadpony.justify.internal.schema.io.AbstractBasicSchemaReader.readSchema(AbstractBasicSchemaReader.java:96)
	at org.leadpony.justify.internal.schema.io.AbstractSchemaReader.read(AbstractSchemaReader.java:49)
	at org.leadpony.justify.internal.schema.io.AbstractProbeSchemaReader.readSchema(AbstractProbeSchemaReader.java:48)
	at org.leadpony.justify.internal.schema.io.AbstractSchemaReader.read(AbstractSchemaReader.java:49)
	at org.leadpony.justify.api.JsonValidationService.readSchema(JsonValidationService.java:174)
	at com.darichey.test.Test.lambda$readSchema$0(Test.java:33)
	at org.leadpony.justify.internal.schema.io.AbstractBasicSchemaReader.resolveSchema(AbstractBasicSchemaReader.java:247)
	at org.leadpony.justify.internal.schema.io.AbstractBasicSchemaReader.dereferenceSchema(AbstractBasicSchemaReader.java:237)
	at org.leadpony.justify.internal.schema.io.AbstractBasicSchemaReader.resolveAllReferences(AbstractBasicSchemaReader.java:215)
	at org.leadpony.justify.internal.schema.io.AbstractBasicSchemaReader.postprocess(AbstractBasicSchemaReader.java:189)
	at org.leadpony.justify.internal.schema.io.AbstractBasicSchemaReader.readSchema(AbstractBasicSchemaReader.java:94)
	at org.leadpony.justify.internal.schema.io.AbstractSchemaReader.read(AbstractSchemaReader.java:49)
	at org.leadpony.justify.internal.schema.io.AbstractProbeSchemaReader.readSchema(AbstractProbeSchemaReader.java:48)
	at org.leadpony.justify.internal.schema.io.AbstractSchemaReader.read(AbstractSchemaReader.java:49)
	at com.darichey.test.Test.readSchema(Test.java:37)
	at com.darichey.test.Test.test(Test.java:21)
	at com.darichey.test.Test.main(Test.java:15)
```
As you can see, there is no issue validating `baz.json` and `bar.json`, but validating `foo.json` fails to resolve the reference to `baz.json`. 

Modifying the resolver to:
```java
.withSchemaResolver(id -> {
    System.out.println(id.getPath());
    return service.readSchema(Paths.get("schema", id.getPath()));
})
```
outputs
```
{"qux":3}
baz.schema.json
{"baz":{"qux":3}}
bar.schema.json
[ above exception ]
```
which seems to show that the resolver is never invoked for `baz.schema.json`. Is there a different way I am supposed to do this?

**Comment by leadpony** [comment]
Thank for contacting me.
You attatch your resolver to the factory and use the factory to read the first schema. However the factory is not used when reading the referenced schemas. Please look at the lambda expression part in your code thoroughly.
Thank you.

**Comment by leadpony** [comment]
I will improve the official example later to support the chained resolution as you are trying.

**Comment by darichey** [comment]
Of course, it is impossible to refer to `factory` within this expression. How should I ensure that reading a schema normally and reading a schema within the resolver use the same resolver?

**Comment by leadpony** [comment]
Hello @darichey 
I have improved the code of  [Schema Resolver example](https://github.com/leadpony/justify-examples/tree/master/justify-examples-schemaresolver) so that it can read the referenced schema which need to resolve another schema. I would like you to use this as a reference.

**Comment by darichey** [comment]
Thanks!
