### ISSUE TITLE
justify-cli jar from maven repo seems to be missing a dependency

### ISSUE THREAD

**Issue by jbrazile** [leadpony/justify#44]
$ wget  https://repo1.maven.org/maven2/org/leadpony/justify/justify-cli/2.0.0/justify-cli-2.0.0.jar
$ java -jar justify-cli-2.0.0.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: org/fusesource/jansi/AnsiConsole
        at org.leadpony.justify.cli.Launcher.createConsole(Launcher.java:64)
        at org.leadpony.justify.cli.Launcher.launch(Launcher.java:46)
        at org.leadpony.justify.cli.Launcher.launch(Launcher.java:42)
        at org.leadpony.justify.cli.Launcher.main(Launcher.java:83)
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.AnsiConsole
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 4 more

**Comment by leadpony** [comment]
@jbrazile 
Justify CLI with all dependencies can be downloaded from [Release](https://github.com/leadpony/justify/releases)  in GitHub. Please try it.

**Comment by jbrazile** [comment]
Ahh, I assumed it was a standalone executable jar.  
The download indeed includes 17 files/directories which allows it to work.

**Comment by jbrazile** [comment]
In case anyone wants a simple, standalone, single jar option (leadpony's cli is much more complete), I threw one together here:  https://github.com/jbrazile/jjval
